 stages:
   - test
   - package
   - build

 before_script:
   - docker stop petclinic_run
   - chmod +x mvnw
   - docker stop pets_db
   - docker rm pets_db
   - docker stop test_pets_db
   - docker rm test_pets_db

 after_script:
   - docker-compose up -d
   - docker-compose start


 Test project:
   stage: test
   only:
     - merge-requests
     - master
   script:
     - ./mvnw test

 Package project:
   stage: package
   script:
     - ./mvnw package -Dmaven.test.skip=true
   only:
     - master
   artifacts:
     paths:
       - web/target/*.jar
     expire_in: 3 days

 Build project:
   stage: build
   only:
     - master
   script:
     - docker rmi $(docker images -f dangling=true -q) || true
     - docker build -t petclinic:0.0.1 .








