 stages:
   - test
   - package
   - build

 before_script:
   - docker stop petclinic_run
   - chmod +x mvnw


 after_script:
   - docker-compose up -d
   - docker-compose start


 Test project:
   stage: test
   only:
#     - merge-requests
     - 89-devops
   script:
     - mvn -Dtest="com/vet24/web/**" test
     - ./mvnw test

 Package project:
   stage: package
   script:
     - ./mvnw package -Dmaven.test.skip=true
   only:
     - 89-devops
   artifacts:
     paths:
       - web/target/*.jar
     expire_in: 3 days

 Build project:
   stage: build
   only:
     - 89-devops
   script:
     - docker rmi $(docker images -f dangling=true -q) || true
     - docker build -t petclinic:0.0.1 .
     - docker stop pets_db
     - docker rm pets_db
     - docker stop test_pets_db
     - docker rm test_pets_db








