stages:
  - test
  - build
cache:
  paths:
    - .m2/repository

building:
  stage: build
  before_script:
    - docker-compose down
    - docker image prune -a -f
    - docker-compose build
  script:
    - docker-compose up -d
  after_script:
    - docker image prune -f
  tags:
    - clinic_shell
  rules:
    - if: $CI_MERGE_REQUEST_IID




test_maven:
  stage: test
  script:
    - mvn clean test
  tags:
    - clinic_docker_runner
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'






