 stages:
   - test
   - package
   - build

 before_script:
   - docker stop petclinic_run
   - chmod +x mvnw

# after_script:
#   - docker-compose up -d

 Test project:
   stage: test
   only:
     - 89-devops
   script:
     - ./mvnw test

 Package project:
   stage: package
   script:
    - ./mvnw package -Dmaven.test.skip=true
   only:
     - 89-devops
   artifacts:
     paths:
       - web/target/*.jar
     expire_in: 3 days

 Build project:
  stage: build
  only:
   - 89-devops
  script:
  - docker stop $(docker ps -a -q)
   - docker rm $(docker ps -a -q)
 # - docker rmi $(docker images -f dangling=true -q) || true
  - docker build -t petclinic:0.0.1 .

