stages:
  - sonar-check
  - test
  - build

building:
  stage: build
  before_script:
    - docker-compose down
    - docker image prune -a -f
    - docker-compose build
  script:
    - docker-compose up -d
  after_script:
    - docker image prune -f
  tags:
    - clinic_shell
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'

sonarqube-check:
  stage: sonar-check
  variables:
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
    SONAR_TOKEN: "4819dd90b912c5417be7c6551950ad6becbc1fc6"
    SONAR_HOST_URL: "http://91.241.64.154:9000"
    SONAR_PROJECT_KEY: "pet_clinic"
  script:
    - mvn test -P test_prod sonar:sonar -e -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN
  tags:
    - clinic_docker_runner
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "master"


test_maven:
  stage: test
  script:
    - mvn clean test -P test_prod
  tags:
    - clinic_docker_runner
  artifacts:
    reports:
      junit:
        - web/target/surefire-reports/TEST-*.xml
        - web/target/failsafe-reports/TEST-*.xml
  rules:
    - if: $CI_MERGE_REQUEST_IID






